module.exports = [
  {
   table: 'ST_ARTICULOS',
   column: [  {"COLUMN_NAME":"COD_EMPRESA"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_ARTICULO"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"DESCRIPCION"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_PAIS_ORIGEN"    ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_MARCA"          ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_RUBRO"          ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_FAMILIA"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_LINEA"          ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_ENVASE"         ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_IVA"            ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_MANEJA_STOCK"   ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COSTO_FOB"          ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COD_MONEDA_COSTO"   ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"FEC_ULTIMA_COMP"    ,	"DATA_TYPE":"DATE"       },
              {"COLUMN_NAME":"COD_PROVEEDOR_DFLT" ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_ORIGEN_ART"     ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"ESTADO"             ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"PRECIO_BASE"        ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COD_MONEDA_BASE"    ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_BARRA_ART"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_MODIFICA_PRECIO",	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"PORC_DESCUENTO"     ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COMENTARIO"         ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_GRUPO"          ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"MANEJA_COSTO"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_MANEJA_LOTES"   ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"TIP_CAMBIO_US"      ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COD_ALTERNO"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"FEC_ALTA"           ,	"DATA_TYPE":"DATE"       },
              {"COLUMN_NAME":"IND_PRECIOS"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_ENVASE"         ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"FEC_ULTIMA_VENTA"   ,	"DATA_TYPE":"DATE"       },
              {"COLUMN_NAME":"COD_USUARIO_ALTA"   ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"FEC_MODI"           ,	"DATA_TYPE":"DATE"       },
              {"COLUMN_NAME":"COD_USUARIO_MODI"   ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"NRO_REGISTRO"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_COMPRA"         ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_VENTA"          ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_CUENTA_GASTO"   ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"PORC_UTILIDAD"      ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"PORC_RECARGO"       ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"PRECIO_BASE_ANT"    ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"IND_UM_BASICA"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COSTO_PROM_GS"      ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_ULTIMO_GS"    ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_PROM_US"      ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_ULTIMO_US"    ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"GASTO_ULTIMO_GS"    ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_ULTIMO_RS"    ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"TIP_CAMBIO_RS"      ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_PROM_ANT_GS"  ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_PROM_ANT_US"  ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_ULT_ANT_GS"   ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COSTO_ULT_ANT_US"   ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"TIP_PRODUCTO"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_RUBRO_ANT"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"ETIQUETA"           ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_VENTA_MOB"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"INSCRIPCION"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"NRO_ORDEN"          ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"IND_COND_VTA"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_REST_VENTA"     ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_CATEGORIA"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_CAT_ALM"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_CAT_SEP"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_CAT_REP"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_CAT_EMP"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_TRANSPORTE"     ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_RRHH"           ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_MANEJA_VTO"     ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_INPASA"         ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"DESC_UNID_MED"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COD_GRUPO_ART"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"VER_CATASTRO"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_JNJ"            ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_ESPECIAL"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"ART_ADICIONAL"      ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_MED_COMP"       ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"CANT_PED"           ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"CANT_BASE"          ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"IND_MES"            ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"COND_COMPRA"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"CANT_VOLUMEN"       ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"COD_NOMEN"          ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"IND_REGIMEN"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"CANTIDAD_CONT"      ,	"DATA_TYPE":"NUMBER"     },
              {"COLUMN_NAME":"TIPO_COMPRA"        ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"TIP_NEG"            ,	"DATA_TYPE":"VARCHAR2"   },
              {"COLUMN_NAME":"NAME_IMG"           ,	"DATA_TYPE":"VARCHAR2"   },
            ],
    pk: [ { COLUMN_NAME: 'COD_EMPRESA'   , POSITION: 1 },
          { COLUMN_NAME: 'COD_ARTICULO'  , POSITION: 2 }
        ],
   },{
    table: 'ST_RELACIONES',
    column: [ {"COLUMN_NAME":"COD_EMPRESA"          ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"COD_ARTICULO"         ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"COD_UNIDAD_REL"       ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"REFERENCIA"           ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"MULT"                 ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"DIV"                  ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"IND_BASICO"           ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"IND_PORC_VTA"         ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"IND_PRECIO_VENDEDOR"  ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"IND_PRECIO_SALON"     ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"LARGO_M"              ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"ANCHO_M"              ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"ALTO_M"               ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"KG_PESO_BRUTO"        ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"KG_PESO_NETO"         ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"VOLUMEN"              ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"IND_VENTA"            ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"COD_BARRA_ART"        ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"LASTRO"               ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"CAPAS"                ,	"DATA_TYPE":"NUMBER"    },
              {"COLUMN_NAME":"MEN_UN_VTA"           ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"UNIMED"               ,	"DATA_TYPE":"VARCHAR2"  },
              {"COLUMN_NAME":"DESUNIMED"            ,	"DATA_TYPE":"VARCHAR2"  },
            ],
    pk:[
        { COLUMN_NAME: 'COD_EMPRESA'    , POSITION: 1 },
        { COLUMN_NAME: 'COD_ARTICULO'   , POSITION: 2 },
        { COLUMN_NAME: 'COD_UNIDAD_REL' , POSITION: 3 },
        { COLUMN_NAME: 'IND_BASICO'     , POSITION: 4 },
      ]
  }]