
module.exports = [
  {
    table: 'VT_COMPROBANTES_CABECERA',
    column:[{"COLUMN_NAME":"COD_EMPRESA"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIP_COMPROBANTE"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"SER_COMPROBANTE"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_COMPROBANTE"          ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"COD_SUCURSAL"             ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"FEC_COMPROBANTE"          ,	"DATA_TYPE":"DATE"      },          
            {"COLUMN_NAME":"COD_CLIENTE"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_VENDEDOR"             ,	"DATA_TYPE":"VARCHAR2"  },            
            {"COLUMN_NAME":"TIP_COMPROBANTE_REF"      ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"SER_COMPROBANTE_REF"      ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_COMPROBANTE_REF"      ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"COD_CONDICION_VENTA"      ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_LISTA_PRECIO"         ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"DESCUENTO"                ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"COD_MONEDA"               ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIP_CAMBIO"               ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TOT_COMPROBANTE"          ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TOT_GRAVADAS"             ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TOT_EXENTAS"              ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TOT_IVA"                  ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"NRO_MOV_CAJ"              ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"ESTADO"                   ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"FEC_ESTADO"               ,	"DATA_TYPE":"DATE"      },
            {"COLUMN_NAME":"COD_USUARIO"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"FEC_ALTA"                 ,	"DATA_TYPE":"DATE"      },
            {"COLUMN_NAME":"NOM_CLIENTE"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"ESTADO_REPARTO"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COMENTARIO"               ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"GRU_COMPROBANTE"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIP_MOV_CAJ"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"REFERENCIA"               ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TEL_CLIENTE"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"SER_MOV_CAJ"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"RUC"                      ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"DIR_CLIENTE"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_USUARIO_ANU"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_MOTIVO_ANU"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_USUARIO_MODI"         ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"FEC_MODI"                 ,	"DATA_TYPE":"DATE"      },
            {"COLUMN_NAME":"IND_REPARTO"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"FEC_VENCIMIENTO"          ,	"DATA_TYPE":"DATE"      },
            {"COLUMN_NAME":"COD_MOTIVO_NCR"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_ASIENTO"              ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TIP_CAMBIO_US"            ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TOT_PESO"                 ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"NRO_PLANILLA"             ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"FEC_CIERRE"               ,	"DATA_TYPE":"DATE"      },
            {"COLUMN_NAME":"COD_ZONA"                 ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_DEPOSITO"             ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_SUBCLIENTE"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NOM_SUBCLIENTE"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIP_REFERENCIA"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"SER_REFERENCIA"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_REFERENCIA"           ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"PORC_DESC_VAR"            ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"PORC_DESC_FIN"            ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"DESCUENTO_VAR"            ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"DESCUENTO_FIN"            ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"CI"                       ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_GENERICO"             ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"VENDEDOR_PERSONA"         ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_SUPERVISOR"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"SUPERVISOR_PERSONA"       ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"BLOQ_X_VENT_PROG"         ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_TELEV"                ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"LIMITE_CREDITO"           ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"SALDO"                    ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"CLIENTE_PERSONA"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"OBSERVACION"              ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_NCR_CLIENTE"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_BLOQUEADO"            ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_REFACTURADO"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_ENTREGADO"            ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_ODM"                  ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COD_MONEDA_REF"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIP_CAMBIO_REF"           ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"TOT_COMPROBANTE_REF"      ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"IND_VENTA"                ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"COBRAR_EFE"               ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_ORDEN_COMPRA"         ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_TIMBRADO"             ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"FEC_FACTURA"              ,	"DATA_TYPE":"DATE"      },
            {"COLUMN_NAME":"IMP_COMP_INPASA"          ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_ROTACION"             ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_INPASA"               ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"MONTO_TOT_DIF"            ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"IND_CLIENTE_APOLO"        ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TOT_COMPROBANTE_ANT"      ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"SER_INPASA"               ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"DESC_VAR_PREC_DIF"        ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"DESC_FIN_PREC_DIF"        ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"IND_PRESENCIAL"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIPO"                     ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIP_VTA_GANADO"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_PROC_SIFEN"           ,	"DATA_TYPE":"VARCHAR2"  },          
            {"COLUMN_NAME":"NRO_CDC"                  ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_TICKET"               ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"PROC_CANCELACION"         ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"CON_NCE"                  ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"TIPTRA"                   ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"NRO_INPASA"               ,	"DATA_TYPE":"NUMBER"    },
            {"COLUMN_NAME":"NRO_CDC_INPASA"           ,	"DATA_TYPE":"VARCHAR2"  },
            {"COLUMN_NAME":"IND_PROC_SIFEN_INP"       ,	"DATA_TYPE":"VARCHAR2"  }
          ],
   pk:   [{ COLUMN_NAME: 'COD_EMPRESA'    , POSITION: 1 },
          { COLUMN_NAME: 'TIP_COMPROBANTE', POSITION: 2 },
          { COLUMN_NAME: 'SER_COMPROBANTE', POSITION: 3 },
          { COLUMN_NAME: 'NRO_COMPROBANTE', POSITION: 4 }
          ],
  },  
  {
    table: 'VT_COMPROBANTES_DETALLE',
    column:[{"COLUMN_NAME":"COD_EMPRESA"               , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"TIP_COMPROBANTE"           , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"SER_COMPROBANTE"           , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_COMPROBANTE"           , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COD_ARTICULO"              , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"CANTIDAD"                  , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"PRECIO_UNITARIO"           , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"MONTO_TOTAL"               , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"TOTAL_IVA"                 , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COSTO_PROMEDIO"            , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"CANTIDAD_UB"               , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COD_UNIDAD_MEDIDA"         , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_ORDEN"                 , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"NRO_LOTE"                  , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"PORC_IVA"                  , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COD_IVA"                   , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"PRECIO_UNITARIO_C_IVA"     , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"TIP_COMPROBANTE_REF"       , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"SER_COMPROBANTE_REF"       , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_COMPROBANTE_REF"       , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"NRO_ORDEN_REF"             , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"PRECIO_UB"                 , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COSTO_ULTIMO"              , "DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COD_DEPOSITO"              , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"IND_MANEJA_STOCK"          , "DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"PORC_COMISION"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COD_SUCURSAL"              ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"MONTO_TOTAL_C_IVA"         ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PORC_DESC_VAR"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PORC_DESC_FIN"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"DESCUENTO_VAR"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"DESCUENTO_FIN"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"FEC_VENCIMIENTO"           ,	"DATA_TYPE":"DATE"    },
            {"COLUMN_NAME":"PRECIO_LISTA"              ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PRECIO_MIN"                ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"IND_BLOQUEADO"             ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"COD_UM"                    ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"COD_LINEA"                 ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"PORC_COMISION_SUPERVISOR"  ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PORC_NEG"                  ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PRECIO_NEG"                ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PRECIO_DIFERENCIA"         ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"MONTO_TOT_DIF"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"TIPO_PROMOCION"            ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"NRO_PROMOCION"             ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"MONTO_TOTAL_ANT"           ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COD_CLIENTE_REF"           ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"COD_SUBCLIENTE_REF"        ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"DESC_VAR_PREC_DIF"         ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"DESC_FIN_PREC_DIF"         ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"IND_BON"                   ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"IND_BON_CAU"               ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"PORC_GRAVADA"              ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PESO"                      ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"TOTAL_PESO"                ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PESO_MUERTO"               ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"TOTAL_PESO_MUERTO"         ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PORC_UTILIDAD"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PESO_DESBASTE"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"TOTAL_PESO_DESBASTE"       ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"PORC_DESBASTE"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COSTO_DIRECTO"             ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COMENTARIO"                ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"TIP_FACTURA_REF"           ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"SER_FACTURA_REF"           ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"NRO_FACTURA_REF"           ,	"DATA_TYPE":"NUMBER"  }],
   pk:   [{ COLUMN_NAME: 'COD_EMPRESA'    , POSITION: 1 },
          { COLUMN_NAME: 'TIP_COMPROBANTE', POSITION: 2 },
          { COLUMN_NAME: 'SER_COMPROBANTE', POSITION: 3 },
          { COLUMN_NAME: 'NRO_COMPROBANTE', POSITION: 4 },
          { COLUMN_NAME: 'NRO_ORDEN'      , POSITION: 5 },
          ],
  },  
]