
module.exports = [{
    table: 'CC_MOVIMIENTOS_CAJAS',
    column:[  { "COLUMN_NAME":"COD_EMPRESA"     , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"COD_SUCURSAL"    , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"TIP_MOV_CAJ"     , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"SER_MOV_CAJ"     , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"NRO_MOV_CAJ"     , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"FEC_MOV_CAJ"     , "DATA_TYPE":"DATE"    },
              { "COLUMN_NAME":"COD_CAJA"        , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"NRO_HABILITACION", "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"NUM_ASIENTO"     , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"ANULADO"         , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"FEC_ANULACION"   , "DATA_TYPE":"DATE"    },
              { "COLUMN_NAME":"COD_USUARIO"     , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"NRO_CUENTA"      , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"TOT_NRO_MOV_CAJ" , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"COD_MONEDA"      , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"TIPO_CAMBIO"     , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"TIP_CAMBIO"      , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"FEC_ALTA"        , "DATA_TYPE":"DATE"    },
              { "COLUMN_NAME":"COD_CLIENTE"     , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"DESC_CLIENTE"    , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"COD_SUBCLIENTE"  , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"DIFERENCIA"      , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"NRO_COMPR_REF"   , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"TIP_COMPR_REF"   , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"SER_COMPR_REF"   , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"APLI_NCR_PARCIAL", "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"NRO_ASIENTO"     , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"TIP_CAMBIO_US"   , "DATA_TYPE":"NUMBER"  },
              { "COLUMN_NAME":"OBSERVACION"     , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"IND_CIERRE"      , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"IND_EXCEPCION"   , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"IND_APLICADO"    , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"NRO_BOLETA"      , "DATA_TYPE":"VARCHAR2"},
              { "COLUMN_NAME":"IND_INPASA"      , "DATA_TYPE":"VARCHAR2"},
          ],
   pk:   [  { COLUMN_NAME: 'COD_EMPRESA' , POSITION: 1 },
            { COLUMN_NAME: 'TIP_MOV_CAJ' , POSITION: 2 },
            { COLUMN_NAME: 'SER_MOV_CAJ' , POSITION: 3 },
            { COLUMN_NAME: 'NRO_MOV_CAJ' , POSITION: 4 }
         ],
  },{
    table: 'CC_MOVIMIENTOS_COMP',
    column:[{"COLUMN_NAME":"COD_EMPRESA"       ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"TIP_MOV_CAJ"       ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"SER_MOV_CAJ"       ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"NRO_MOV_CAJ"       ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COD_MONEDA"        ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"TIP_CAMBIO"        ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"TIP_COMPROBANTE"   ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"SER_COMPROBANTE"   ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"NRO_COMPROBANTE"   ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COD_CLIENTE"       ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"NRO_CUOTA"         ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"COD_SUBCLIENTE"    ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"TOT_COMPROBANTE"   ,	"DATA_TYPE":"NUMBER"  },
            {"COLUMN_NAME":"NRO_CUENTA_CLIENTE",	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"COD_BANCO_CLIENTE" ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"TIP_PLANILLA"      ,	"DATA_TYPE":"VARCHAR2"},
            {"COLUMN_NAME":"NRO_PLANILLA"      ,	"DATA_TYPE":"NUMBER"  }
          ],
   pk:   [{ COLUMN_NAME: 'COD_EMPRESA'     , POSITION: 1 },
          { COLUMN_NAME: 'TIP_MOV_CAJ'     , POSITION: 2 },
          { COLUMN_NAME: 'SER_MOV_CAJ'     , POSITION: 3 },
          { COLUMN_NAME: 'NRO_MOV_CAJ'     , POSITION: 4 },
          { COLUMN_NAME: 'TIP_COMPROBANTE' , POSITION: 5 },
          { COLUMN_NAME: 'SER_COMPROBANTE' , POSITION: 6 },
          { COLUMN_NAME: 'NRO_COMPROBANTE' , POSITION: 7 }],
  },{
    table: 'CC_FORMAS_COBROS',
    column:[{"COLUMN_NAME":"COD_EMPRESA"          ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"COD_SUCURSAL"         ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"TIP_MOV_CAJ"          ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"SER_MOV_CAJ"          ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_MOV_CAJ"          ,	"DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"NRO_SECUENCIA"        ,	"DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"TIPO_TRANS"           ,	"DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"SUB_TIPO_TRANS"       ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"COD_PER_JURIDICA"     ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_CUENTA"           ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"COD_MONEDA_COBRO"     ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"TIP_CAMBIO"           ,	"DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"FEC_EMISION"          ,	"DATA_TYPE":"DATE"     },
            {"COLUMN_NAME":"FEC_VENCIMIENTO"      ,	"DATA_TYPE":"DATE"     },
            {"COLUMN_NAME":"TIP_DOCUMENTO"        ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"SER_DOCUMENTO"        ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_DOCUMENTO"        ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_CUENTA_CAJA_CHICA",	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"COD_BANCO_CAJA_CHICA" ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"COD_USUARIO"          ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"MONTO"                ,	"DATA_TYPE":"NUMBER"   },
            {"COLUMN_NAME":"COD_BANCO_CLIENTE"    ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NOM_CLIENTE"          ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_CUENTA_ANT"       ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_CUENTA_DEP"       ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_IDENTIFICACION"   ,	"DATA_TYPE":"VARCHAR2" },
            {"COLUMN_NAME":"NRO_FACTURA"          ,	"DATA_TYPE":"VARCHAR2" },
          ],
   pk:   [{ COLUMN_NAME: 'COD_EMPRESA'   , POSITION: 1 },
          { COLUMN_NAME: 'TIP_MOV_CAJ'   , POSITION: 2 },
          { COLUMN_NAME: 'SER_MOV_CAJ'   , POSITION: 3 },
          { COLUMN_NAME: 'NRO_MOV_CAJ'   , POSITION: 4 },
          { COLUMN_NAME: 'NRO_SECUENCIA' , POSITION: 5 }],
  }]